[[redirects]]
  from = "/cgi-center/*"
  to = "https://smartpole.baogao-ipark.ntpc.gov.tw/cgi-center/:splat"
  status = 200

[[redirects]]
  from = "/resource-center/*"
  to = "https://smartpole.baogao-ipark.ntpc.gov.tw/resource-center/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/en-US/index.html"
  status = 200

[[redirects]]
  from = "/en-US/*"
  to = "/en-US/index.html"
  status = 200

[[redirects]]
  from = "/zh-Hant/*"
  to = "/zh-Hant/index.html"
  status = 200
