[[redirects]]
  from = "en-US/cgi-center/*"
  to = "https://smartpole.baogao-ipark.ntpc.gov.tw/cgi-center/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  # headers = {X-From = "Netlify"}

[[redirects]]
  from = "en-US/resource-center/*"
  to = "https://smartpole.baogao-ipark.ntpc.gov.tw/resource-center/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "en-US/*"
  to = "en-US/index.html"
  status = 200
  force = true # COMMENT: ensure that we always redirect
