[[redirects]]
  from = "/cgi-center/*"
  to = "https://smartpole.baogao-ipark.ntpc.gov.tw/cgi-center/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  # headers = {X-From = "Netlify"}

[[redirects]]
  from = "/resource-center/*"
  to = "https://smartpole.baogao-ipark.ntpc.gov.tw/resource-center/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
